# Generated by Django 6.0.5 on 2026-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('score', models.IntegerField()),
                ('difficulty', models.CharField(default='easy', max_length=20)),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
